project:
  type: website

website:
  title: "SingleCellCourse"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - install.qmd
      - schedule.qmd
      - resources.qmd
      - help.qmd
      - extra.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

editor: visual

